# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd23470c9fca6c8bdeeb31fec72e5f0f9676fec21d8ab8dfdaedf5379669ad32a131659adc653b56a9c824d65eafa60cff6475c1062f73a522b49770959b5317

test:
  secret_key_base: 6ae22bd538759754089e783999b9a16a0e13c6223129f23f90b39d7c6998baa2774880d38cc2e47bf64ce92c59a865cc9646540b2a29b0a77da97f2af79cc1cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
